### ISSUE TITLE
Support Multiple Olli Instances on a Single Page

### ISSUE THREAD

**Issue by Matt-Blanco** [umwelt-data/olli#26]
https://github.com/mitvis/olli/blob/1f39e63619b09068fd12872fb4f0f559188071ae/packages/core/src/index.ts#L46

Right now pressing _t_ will only select the first Olli instance. Update to iterate through all instances accessible renderings.

**Comment by jonathanzong** [comment]
resolved in https://github.com/mitvis/olli/commit/19a8344f1df40e6286e8704152ae9b88557788cc
