### ISSUE TITLE
implement targeted navigation

### ISSUE THREAD

**Issue by jonathanzong** [umwelt-data/olli#46]
targeted nav prototype: https://mitvis.github.io/access-interaction/prototypes/jzong/random-access

Targeted navigation is when the user can use a series of dropdowns to directly jump to a known location, rather than pathing there with the arrow keys.

Steps to implement targeted navigation:

- in OlliRuntimeTreeItem, add an event listener for the shortcut ('r' for now)
- copy and modify the openSelectionDialog or openTableDialog functions to create a targeted nav menu containing dropdowns
    - (generating the dropdowns will require some tree traversal that we can talk about)
- in onOk, set focus to the selected location in the tree

**Comment by lpanda2** [comment]
> in onOk, set focus to the selected location in the tree

What's a good way to do this?

**Comment by jonathanzong** [comment]
the relevant function is `tree.setFocusToItem(treeItem)`, and you can look at `openSelectionDialog` for an example of making an `onOk` callback. will need a way to get the corresponding treeitem to whatever is selected in the menu to pass into `setFocusToItem`.

**Comment by jonathanzong** [comment]
closed by https://github.com/mitvis/olli/pull/82
